### ISSUE TITLE
Interpret.cpp L281 -- modify equation() to convert infix expressions to postfix

### ISSUE THREAD

**Issue by RCTMASTA** [RCTMASTA/csis280proj#3]
https://github.com/RCTMASTA/csis280proj/blob/4f3083bfc3caac833f7b63629ea3898e2248b3ee/Interpret.cpp#L281-L337

I copied the pseudocode from the Project.doc that Tony provided, for simplicity's sake.

**Comment by RCTMASTA** [comment]
6cffbb7 : 
* https://github.com/RCTMASTA/csis280proj/blob/6cffbb76f6a0b5daa578f259449a3f165d00dfce/Interpret.cpp#L292 is "nextToken(exp)" the correct interpretation of "for (each character ch in the infix expression)"?

.
* https://github.com/RCTMASTA/csis280proj/blob/6cffbb76f6a0b5daa578f259449a3f165d00dfce/Interpret.cpp#L294 https://github.com/RCTMASTA/csis280proj/blob/6cffbb76f6a0b5daa578f259449a3f165d00dfce/Interpret.cpp#L300 there are multiple possible conditions here for "operand" and "operator" and you can't use ambiguous operators like || in a case statement. how can we implement this?

**Comment by RCTMASTA** [comment]
i was thinking for operator we could do
```
case '+':
case '-':
case '/':
case '*':
<statements>
break;
```
it's hacky as hell but I think it might be the best way to do it...

**Comment by kammitama5** [comment]
LOL. Not hacky. If it works, why not. As long as it isn't already used, why not try it.

**Comment by RCTMASTA** [comment]
https://gist.github.com/mycodeschool/7867739

useful code i found that should help us implement.

**Comment by RCTMASTA** [comment]
Close #3 via 77e1b99 .
Note that this is only _tentatively correct_ since we can't actually test it to make sure it works if/when we finish execute().
